name: Test server

on:
  push:
    branches: ['latest']
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
      # -
      #   name: Run Mage
      #   uses: magefile/mage-action@v3
      #   with:
      #     version: latest
      #     args: deploy:test 240100-tt-mail
      #     workdir: jobs/deploy
      #     install-only: false
      - 
        name: Setup .NET 8.x
        uses: actions/setup-dotnet@v3
        with:
          # Semantic version range syntax or exact version of a dotnet version
          dotnet-version: '8.x'
      -
        name: Check .NET version
        shell: bash
        run: |
          dotnet --version
